#!/bin/sh
set -e

case "$1" in
    purge)
        if dpkg-statoverride --list /usr/bin/sign >/dev/null 2>&1; then
            dpkg-statoverride --remove /usr/bin/sign
        fi
        ;;
esac

# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'obs-signd.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0

