#!/bin/sh
set -e

case "$1" in
    configure)
        if ! getent group obsrun >/dev/null; then
            addgroup --system obsrun
        fi
        if ! getent passwd obsrun >/dev/null; then
            adduser --system --ingroup obsrun --home /var/lib/obs-signd --no-create-home --shell /usr/sbin/nologin obsrun
        fi
        if ! dpkg-statoverride --list /usr/bin/sign >/dev/null 2>&1; then
            dpkg-statoverride --add root obsrun 4750 /usr/bin/sign
        fi
        ;;
esac

# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'obs-signd.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'obs-signd.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'obs-signd.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'obs-signd.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'obs-signd.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0

